### ISSUE TITLE
Just to know, why do we need 3.19 kernel

### ISSUE THREAD

**Issue by thbeh** [mediative/mesos-stack#35]
Hi, I am looking at something similar to run on baremetal and I am testing now with vagrant. Just a question of curiosity, why is 3.19 needed, is it because vivid uses systemd instead of upstart?

**Comment by jonas** [comment]
Hello, we had stability issues when running newer Docker version on the default kernel provided Ubuntu 14.04.

**Comment by thbeh** [comment]
Thanks
